/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cecar.developertest.views;

import edu.cecar.developertest.models.Person;
import edu.cecar.developertest.views.helpers.ObjectTableModel;

import java.awt.event.MouseEvent;
import javax.swing.table.TableModel;

/**
 *
 * @author sgioh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas = new javax.swing.JPanel();
        pnNavigation = new javax.swing.JPanel();
        btnUserSearch = new javax.swing.JPanel();
        iconUserSearchOption = new javax.swing.JLabel();
        btnUserDownload = new javax.swing.JPanel();
        iconUserDownloadOption = new javax.swing.JLabel();
        btnUserRegistration = new javax.swing.JPanel();
        iconUserRegistrationOption = new javax.swing.JLabel();
        pnTiitleBar = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        btnExitApp = new javax.swing.JPanel();
        iconExitAppOption = new javax.swing.JLabel();
        pnBook = new javax.swing.JLayeredPane();
        pgUserDownload = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        btnLoadUsersData = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        lbUrlError = new javax.swing.JLabel();
        lbTokenError = new javax.swing.JLabel();
        pgUserSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();
        txtQuery = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JLabel();
        pgUserRegistration = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNickName = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLocalUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.setMinimumSize(new java.awt.Dimension(900, 500));
        canvas.setPreferredSize(new java.awt.Dimension(900, 500));

        pnNavigation.setBackground(new java.awt.Color(206, 64, 78));
        pnNavigation.setMaximumSize(new java.awt.Dimension(60, 500));
        pnNavigation.setMinimumSize(new java.awt.Dimension(60, 500));
        pnNavigation.setPreferredSize(new java.awt.Dimension(60, 500));

        btnUserSearch.setBackground(new java.awt.Color(209, 82, 94));
        btnUserSearch.setToolTipText("Buscar usuarios");
        btnUserSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserSearch.setMaximumSize(new java.awt.Dimension(60, 60));
        btnUserSearch.setMinimumSize(new java.awt.Dimension(60, 60));
        btnUserSearch.setName("search"); // NOI18N
        btnUserSearch.setPreferredSize(new java.awt.Dimension(60, 60));
        btnUserSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserSearchMouseReleased(evt);
            }
        });

        iconUserSearchOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/search-on.png"))); // NOI18N

        javax.swing.GroupLayout btnUserSearchLayout = new javax.swing.GroupLayout(btnUserSearch);
        btnUserSearch.setLayout(btnUserSearchLayout);
        btnUserSearchLayout.setHorizontalGroup(
            btnUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserSearchOption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUserSearchLayout.setVerticalGroup(
            btnUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserSearchOption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUserDownload.setBackground(new java.awt.Color(206, 64, 78));
        btnUserDownload.setToolTipText("Sincronizar");
        btnUserDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserDownload.setMaximumSize(new java.awt.Dimension(60, 60));
        btnUserDownload.setMinimumSize(new java.awt.Dimension(60, 60));
        btnUserDownload.setName("sync"); // NOI18N
        btnUserDownload.setPreferredSize(new java.awt.Dimension(60, 60));
        btnUserDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserDownloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserDownloadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserDownloadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserDownloadMouseReleased(evt);
            }
        });

        iconUserDownloadOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/cloud-download-off.png"))); // NOI18N

        javax.swing.GroupLayout btnUserDownloadLayout = new javax.swing.GroupLayout(btnUserDownload);
        btnUserDownload.setLayout(btnUserDownloadLayout);
        btnUserDownloadLayout.setHorizontalGroup(
            btnUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserDownloadOption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUserDownloadLayout.setVerticalGroup(
            btnUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserDownloadOption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUserRegistration.setBackground(new java.awt.Color(206, 64, 78));
        btnUserRegistration.setToolTipText("Usuarios");
        btnUserRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserRegistration.setMaximumSize(new java.awt.Dimension(60, 60));
        btnUserRegistration.setMinimumSize(new java.awt.Dimension(60, 60));
        btnUserRegistration.setName("users"); // NOI18N
        btnUserRegistration.setPreferredSize(new java.awt.Dimension(60, 60));
        btnUserRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserRegistrationMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserRegistrationMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserRegistrationMouseReleased(evt);
            }
        });

        iconUserRegistrationOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/users-off.png"))); // NOI18N
        iconUserRegistrationOption.setMaximumSize(new java.awt.Dimension(40, 40));
        iconUserRegistrationOption.setMinimumSize(new java.awt.Dimension(40, 40));
        iconUserRegistrationOption.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout btnUserRegistrationLayout = new javax.swing.GroupLayout(btnUserRegistration);
        btnUserRegistration.setLayout(btnUserRegistrationLayout);
        btnUserRegistrationLayout.setHorizontalGroup(
            btnUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserRegistrationOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnUserRegistrationLayout.setVerticalGroup(
            btnUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUserRegistrationOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNavigationLayout = new javax.swing.GroupLayout(pnNavigation);
        pnNavigation.setLayout(pnNavigationLayout);
        pnNavigationLayout.setHorizontalGroup(
            pnNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUserRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUserDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnNavigationLayout.setVerticalGroup(
            pnNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pnTiitleBar.setBackground(new java.awt.Color(255, 255, 255));
        pnTiitleBar.setMaximumSize(new java.awt.Dimension(32767, 36));
        pnTiitleBar.setMinimumSize(new java.awt.Dimension(840, 36));
        pnTiitleBar.setPreferredSize(new java.awt.Dimension(840, 36));
        pnTiitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnTiitleBarMouseDragged(evt);
            }
        });
        pnTiitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTiitleBarMousePressed(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setMinimumSize(new java.awt.Dimension(800, 4));
        progressBar.setPreferredSize(new java.awt.Dimension(800, 4));

        btnExitApp.setBackground(new java.awt.Color(255, 255, 255));
        btnExitApp.setMinimumSize(new java.awt.Dimension(30, 30));
        btnExitApp.setPreferredSize(new java.awt.Dimension(30, 30));
        btnExitApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitAppMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitAppMouseReleased(evt);
            }
        });

        iconExitAppOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/exit-off.png"))); // NOI18N

        javax.swing.GroupLayout btnExitAppLayout = new javax.swing.GroupLayout(btnExitApp);
        btnExitApp.setLayout(btnExitAppLayout);
        btnExitAppLayout.setHorizontalGroup(
            btnExitAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitAppLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(iconExitAppOption)
                .addGap(5, 5, 5))
        );
        btnExitAppLayout.setVerticalGroup(
            btnExitAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitAppLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(iconExitAppOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout pnTiitleBarLayout = new javax.swing.GroupLayout(pnTiitleBar);
        pnTiitleBar.setLayout(pnTiitleBarLayout);
        pnTiitleBarLayout.setHorizontalGroup(
            pnTiitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTiitleBarLayout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnTiitleBarLayout.setVerticalGroup(
            pnTiitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTiitleBarLayout.createSequentialGroup()
                .addGroup(pnTiitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTiitleBarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnExitApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pnBook.setBackground(new java.awt.Color(204, 204, 204));
        pnBook.setMinimumSize(new java.awt.Dimension(840, 464));
        pnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgUserDownload.setBackground(new java.awt.Color(255, 255, 255));
        pgUserDownload.setMinimumSize(new java.awt.Dimension(820, 444));
        pgUserDownload.setPreferredSize(new java.awt.Dimension(820, 444));
        pgUserDownload.setVisible(false);

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("Recuperar usuarios");

        separator1.setMinimumSize(new java.awt.Dimension(800, 10));
        separator1.setPreferredSize(new java.awt.Dimension(800, 10));

        label2.setForeground(new java.awt.Color(102, 102, 102));
        label2.setText("Obtener la última versión de la base de datos de usuarios en la nube.");

        label3.setForeground(new java.awt.Color(102, 102, 102));
        label3.setText("URL del servidor");

        txtUrl.setText("https://gorest.co.in/public-api/");
        txtUrl.setEnabled(false);
        txtUrl.setMinimumSize(new java.awt.Dimension(154, 20));
        txtUrl.setName("url"); // NOI18N

        label4.setForeground(new java.awt.Color(102, 102, 102));
        label4.setText("Token de acceso");

        txtToken.setText("0wZiOknooiIHs1-g1ZTFv0b6w9BcpbaUkh47");
        txtToken.setMinimumSize(new java.awt.Dimension(154, 20));
        txtToken.setName("token"); // NOI18N
        txtToken.setPreferredSize(new java.awt.Dimension(154, 20));

        btnLoadUsersData.setText("Recuperar");
        btnLoadUsersData.setMinimumSize(new java.awt.Dimension(154, 23));
        btnLoadUsersData.setName("load"); // NOI18N
        btnLoadUsersData.setPreferredSize(new java.awt.Dimension(154, 23));

        label5.setForeground(new java.awt.Color(102, 102, 102));
        label5.setText("Nota: se perderán todos los usuarios recuperados en la última actualización.");

        btnExport.setText("Exportar");
        btnExport.setMinimumSize(new java.awt.Dimension(154, 23));
        btnExport.setPreferredSize(new java.awt.Dimension(154, 23));

        lbUrlError.setForeground(new java.awt.Color(255, 255, 255));
        lbUrlError.setText("Este campo es necesario.");

        lbTokenError.setForeground(new java.awt.Color(255, 255, 255));
        lbTokenError.setText("Este campo es necesario.");

        javax.swing.GroupLayout pgUserDownloadLayout = new javax.swing.GroupLayout(pgUserDownload);
        pgUserDownload.setLayout(pgUserDownloadLayout);
        pgUserDownloadLayout.setHorizontalGroup(
            pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgUserDownloadLayout.createSequentialGroup()
                .addGroup(pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgUserDownloadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1)
                            .addComponent(label2)))
                    .addGroup(pgUserDownloadLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUrlError)
                            .addGroup(pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label4)
                                .addComponent(label3)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoadUsersData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtToken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbTokenError))))
                .addContainerGap())
        );
        pgUserDownloadLayout.setVerticalGroup(
            pgUserDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgUserDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addGap(9, 9, 9)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lbUrlError)
                .addGap(2, 2, 2)
                .addComponent(label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbTokenError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoadUsersData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(label5)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pnBook.add(pgUserDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pgUserSearch.setBackground(new java.awt.Color(255, 255, 255));
        pgUserSearch.setMinimumSize(new java.awt.Dimension(820, 444));
        pgUserSearch.setPreferredSize(new java.awt.Dimension(820, 444));

        tbUsers.setModel(this.createPersonDataModel());
        jScrollPane1.setViewportView(tbUsers);

        txtQuery.setToolTipText("Para generar una lista de todos los usuarios deje este campo vacío");
        txtQuery.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Búsqueda de usuarios ");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Buscar usuarios por su identificación o generar una lista de todos ellos.");

        jSeparator1.setMinimumSize(new java.awt.Dimension(800, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(800, 10));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/search.png"))); // NOI18N

        javax.swing.GroupLayout pgUserSearchLayout = new javax.swing.GroupLayout(pgUserSearch);
        pgUserSearch.setLayout(pgUserSearchLayout);
        pgUserSearchLayout.setHorizontalGroup(
            pgUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgUserSearchLayout.createSequentialGroup()
                .addGroup(pgUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgUserSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgUserSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(pgUserSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(pgUserSearchLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgUserSearchLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pgUserSearchLayout.setVerticalGroup(
            pgUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pgUserSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pgUserSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnBook.add(pgUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pgUserRegistration.setBackground(new java.awt.Color(255, 255, 255));
        pgUserRegistration.setMinimumSize(new java.awt.Dimension(820, 444));
        pgUserRegistration.setPreferredSize(new java.awt.Dimension(820, 444));
        pgUserRegistration.setVisible(false);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Registrar o eliminar usuarios de la aplicación.");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nombre de usuario:");

        txtNickName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtNickName.setPreferredSize(new java.awt.Dimension(150, 20));

        btnAddUser.setText("Agregar");
        btnAddUser.setMinimumSize(new java.awt.Dimension(150, 23));
        btnAddUser.setPreferredSize(new java.awt.Dimension(150, 23));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Registro de usuarios");

        btnDeleteUser.setText("Eliminar");

        jSeparator2.setMinimumSize(new java.awt.Dimension(800, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(800, 10));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Contraseña:");

        txtPassword.setMinimumSize(new java.awt.Dimension(150, 20));
        txtPassword.setPreferredSize(new java.awt.Dimension(150, 20));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Para eliminar a un usuario, selecciónelo en la tabla y pulse eliminar.");

        tbLocalUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbLocalUsers);

        javax.swing.GroupLayout pgUserRegistrationLayout = new javax.swing.GroupLayout(pgUserRegistration);
        pgUserRegistration.setLayout(pgUserRegistrationLayout);
        pgUserRegistrationLayout.setHorizontalGroup(
            pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8))
                            .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pgUserRegistrationLayout.setVerticalGroup(
            pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pgUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pgUserRegistrationLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteUser)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pnBook.add(pgUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canvasLayout.createSequentialGroup()
                .addComponent(pnNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTiitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(canvasLayout.createSequentialGroup()
                .addComponent(pnTiitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserRegistrationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserRegistrationMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.selectedPageName = evt.getComponent().getName();
            this.setUsersButtonColor();
            this.resetSearchButtonColor();
            this.resetSyncButtonColor();
            this.pgUserRegistration.setVisible(true);
            this.pgUserSearch.setVisible(false);
            this.pgUserDownload.setVisible(false);
        }
    }//GEN-LAST:event_btnUserRegistrationMouseReleased

    private void btnUserRegistrationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserRegistrationMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.resetUsersButtonColor();
        }
    }//GEN-LAST:event_btnUserRegistrationMousePressed

    private void btnUserRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserRegistrationMouseExited
        this.resetUsersButtonColor();
    }//GEN-LAST:event_btnUserRegistrationMouseExited

    private void btnUserRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserRegistrationMouseEntered
        this.setUsersButtonColor();
    }//GEN-LAST:event_btnUserRegistrationMouseEntered

    private void btnUserDownloadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDownloadMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.selectedPageName = evt.getComponent().getName();
            this.setSyncButtonColor();
            this.resetSearchButtonColor();
            this.resetUsersButtonColor();
            this.pgUserDownload.setVisible(true);
            this.pgUserSearch.setVisible(false);
            this.pgUserRegistration.setVisible(false);
        }
    }//GEN-LAST:event_btnUserDownloadMouseReleased

    private void btnUserDownloadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDownloadMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.resetSyncButtonColor();
        }
    }//GEN-LAST:event_btnUserDownloadMousePressed

    private void btnUserDownloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDownloadMouseExited
        this.resetSyncButtonColor();
    }//GEN-LAST:event_btnUserDownloadMouseExited

    private void btnUserDownloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDownloadMouseEntered
        this.setSyncButtonColor();
    }//GEN-LAST:event_btnUserDownloadMouseEntered

    private void btnUserSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.selectedPageName = evt.getComponent().getName();
            this.setSearchButtonColor();
            this.resetSyncButtonColor();
            this.resetUsersButtonColor();
            this.pgUserSearch.setVisible(true);
            this.pgUserDownload.setVisible(false);
            this.pgUserRegistration.setVisible(false);
        }
    }//GEN-LAST:event_btnUserSearchMouseReleased

    private void btnUserSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            this.resetSearchButtonColor();
        }
    }//GEN-LAST:event_btnUserSearchMousePressed

    private void btnUserSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseExited
        this.resetSearchButtonColor();
    }//GEN-LAST:event_btnUserSearchMouseExited

    private void btnUserSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchMouseEntered
        this.setSearchButtonColor();
    }//GEN-LAST:event_btnUserSearchMouseEntered

    private int xx, yy;
    private void pnTiitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTiitleBarMousePressed
        this.xx = evt.getX();
        this.yy = evt.getY();
    }//GEN-LAST:event_pnTiitleBarMousePressed

    private void pnTiitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTiitleBarMouseDragged
        final int x = evt.getXOnScreen();
        final int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_pnTiitleBarMouseDragged

    private void btnExitAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitAppMousePressed
        //btnExit.setBackground(new java.awt.Color(209, 82, 94));
        //iconExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/search-on.png")));
    }//GEN-LAST:event_btnExitAppMousePressed

    private void btnExitAppMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitAppMouseReleased
        System.exit(0);
    }//GEN-LAST:event_btnExitAppMouseReleased

    private String selectedPageName = "";    
    private void setSearchButtonColor() {
        btnUserSearch.setBackground(new java.awt.Color(209, 82, 94));
        iconUserSearchOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/search-on.png")));
    }
    
    private void resetSearchButtonColor() {
        if (!this.selectedPageName.equals(btnUserSearch.getName())) {
            btnUserSearch.setBackground(new java.awt.Color(206, 64, 78));
            iconUserSearchOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/search-off.png")));
        }
    }
    
    private void setSyncButtonColor() {
        btnUserDownload.setBackground(new java.awt.Color(209, 82, 94));
        iconUserDownloadOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/cloud-download-on.png")));
    }

    private void resetSyncButtonColor() {
        if (!this.selectedPageName.equals(btnUserDownload.getName())) {
            btnUserDownload.setBackground(new java.awt.Color(206, 64, 78));
            iconUserDownloadOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/cloud-download-off.png")));
        }
    }
    
    private void setUsersButtonColor() {
        btnUserRegistration.setBackground(new java.awt.Color(209, 82, 94));
        iconUserRegistrationOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/users-on.png")));
    }
    
    private void resetUsersButtonColor() {
        if (!this.selectedPageName.equals(btnUserRegistration.getName())) {
            btnUserRegistration.setBackground(new java.awt.Color(206, 64, 78));
            iconUserRegistrationOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cecar/developertest/views/images/users-off.png")));
        }
    }
    
    private TableModel createPersonDataModel() {
        return new ObjectTableModel<Person>(){

            @Override
            public Object getValueAt(Person person, int columnIndex) {
                switch(columnIndex) {
                    case 0:
                        return person.getFirstName();
                    case 1:
                        return person.getLastName();
                    case 2:
                        return person.getGender();
                    case 3:
                        return person.getDob();
                    case 4:
                        return person.getEmail();
                    case 5:
                        return person.getPhone();
                    case 6:
                        return person.getStatus();
                    case 7:
                        return person.getWebsite();
                }
                return null;
            }

            @Override
            public String getColumnName(int column) {
                switch(column) {
                    case 0:
                        return "Nombre";
                    case 1:
                        return "Apellido";
                    case 2:
                        return "Sexo";
                    case 3:
                        return "Fecha de nacimiento";
                    case 4:
                        return "Email";
                    case 5:
                        return "Teléfono";
                    case 6:
                        return "Estado";
                    case 7:
                        return "Website";
                }
                return null;
            }

            @Override
            public int getColumnCount() {
                return 8;
            }   
        };
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JPanel btnExitApp;
    private javax.swing.JButton btnExport;
    public javax.swing.JButton btnLoadUsersData;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JPanel btnUserDownload;
    private javax.swing.JPanel btnUserRegistration;
    private javax.swing.JPanel btnUserSearch;
    private javax.swing.JPanel canvas;
    private javax.swing.JLabel iconExitAppOption;
    private javax.swing.JLabel iconUserDownloadOption;
    private javax.swing.JLabel iconUserRegistrationOption;
    private javax.swing.JLabel iconUserSearchOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lbTokenError;
    private javax.swing.JLabel lbUrlError;
    private javax.swing.JPanel pgUserDownload;
    private javax.swing.JPanel pgUserRegistration;
    private javax.swing.JPanel pgUserSearch;
    private javax.swing.JLayeredPane pnBook;
    private javax.swing.JPanel pnNavigation;
    private javax.swing.JPanel pnTiitleBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSeparator separator1;
    private javax.swing.JTable tbLocalUsers;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtNickName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtQuery;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
